import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useContractWrite, usePrepareContractWrite } from "wagmi";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import abi from "../abi/abi.json";

const Home: NextPage = () => {
  const { config } = usePrepareContractWrite({
    addressOrName: "0xTODO", // set the address to your contract
    contractInterface: abi,
    functionName: "mintFree",
  });
  const { data, isLoading, isSuccess, write } = useContractWrite(config);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>Welcome to my mint</h1>

        <button
          className={styles.button}
          onClick={() => {
            write?.();
          }}
        >
          Mint
        </button>

        {isLoading && <p>Loading...</p>}
        {isSuccess && <p>Success!</p>}
        {data && (
          <p>
            {JSON.stringify(data)}
            <br />
            <a
              href={`https://goerli.etherscan.io/tx/${data.hash}`}
              target="_blank"
              rel="noreferrer"
              className={styles.button}
              style={{ marginTop: "1rem", display: "inline-block" }}
            >
              View tx on Etherscan
            </a>
          </p>
        )}
      </main>
    </div>
  );
};

export default Home;
